#!/data/data/com.termux/files/usr/bin/bash
# Creates/refreshes the $PREFIX/bin shims for every bare command whose
# real script lives in this folder -- run this once after cloning or
# pulling this repo on a NEW phone (or after pulling updates on either
# one) to make `overseer`, `programs`, etc. work as bare commands there
# too, not just python3 ~/bin/whatever.
#
# Requested directly, after Gabe clarified this device is the A17 (not
# the A33) and that he has both, personal, and wants them kept in
# program-sync: "i want you to keep them both in sync... i mean update
# same programs." Pulling this repo only updates the FILES in ~/bin --
# this script is the other half, wiring bare commands back up to them.
#
#     ~/bin/install.sh
#
# Safe to run as many times as you like -- each shim is just
# overwritten fresh, same as this script already did the first time.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
BIN="/data/data/com.termux/files/usr/bin"

# name -> (CATALOG line, how to launch it)
declare -A CATALOG=(
  [note3]="note3 -- posts a Termux notification with 3 custom buttons you define"
  [opensession]="opensession -- opens a brand-new, independent Termux session running any command"
  [wake]="wake -- looks after you first: mental check, task reminder, diagnostics in one place"
  [mental-check]="mental-check -- how you're feeling: check in, history, hourly reminder, help numbers"
  [task-reminder]="task-reminder -- what you're doing now / were doing, reminder every 20 min"
  [diagnostics]="diagnostics -- everything this phone reports about itself, locally and online"
  [overseer]="overseer -- one dashboard with /help/list/open/newsession, or \`overseer notify\` for a pinned reply notification"
  [programs]="programs -- lists every one of your own commands and starts one -- /help inside it"
  [termux-panel]="termux-panel -- add/remove a swipeable panel of extra keys on Termux's key row"
  [termux-sessions]="termux-sessions -- list/close Termux session tabs (kill <pid>, kill all, or all --include-self)"
  [timeweather]="timeweather -- shows and logs the current time + weather (wttr.in, no API key)"
  [updates]="updates -- check (and pull) GitHub updates for every project here: \`updates\`, \`updates pull <name-or-all>\`"
  [feed]="feed -- a chronological read-only log of everything already tracked here: git, RAM warnings, weather, voice, sync, file moves"
  [relay-file]="relay-file -- pinned notification: Reply saves what you type to a file"
  [relay-claude]="relay-claude -- pinned notification: Reply sends what you type into the claude session"
)
declare -A LAUNCH=(
  [note3]='exec "$HOME/bin/note3" "$@"'
  [opensession]='exec "$HOME/bin/opensession" "$@"'
  [wake]='exec python3 "$HOME/bin/wake" "$@"'
  [mental-check]='exec python3 "$HOME/bin/mental-check" "$@"'
  [task-reminder]='exec python3 "$HOME/bin/task-reminder" "$@"'
  [diagnostics]='exec python3 "$HOME/bin/diagnostics" "$@"'
  [overseer]='exec python3 "$HOME/bin/overseer" "$@"'
  [programs]='exec python3 "$HOME/bin/programs" "$@"'
  [termux-panel]='exec python3 "$HOME/bin/termux-panel" "$@"'
  [termux-sessions]='exec "$HOME/bin/termux-sessions" "$@"'
  [timeweather]='exec "$HOME/bin/timeweather" "$@"'
  [updates]='exec python3 "$HOME/bin/updates" "$@"'
  [feed]='exec python3 "$HOME/bin/feed" "$@"'
  [relay-file]='exec python3 "$HOME/bin/relay-file" "$@"'
  [relay-claude]='exec python3 "$HOME/bin/relay-claude" "$@"'
)

# commands that reuse another command's script (default: same name)
declare -A SOURCE=()

made=0
for name in "${!LAUNCH[@]}"; do
  src="${SOURCE[$name]:-$name}"
  if [ ! -f "$HERE/$src" ]; then
    echo "skipping $name -- $src not found in $HERE" >&2
    continue
  fi
  target="$BIN/$name"
  {
    echo '#!/data/data/com.termux/files/usr/bin/sh'
    echo "# CATALOG: ${CATALOG[$name]}"
    echo "# A thin launcher so \`$name\` works as a bare command -- the actual"
    echo "# script lives at ~/bin/$src. Regenerated by ~/bin/install.sh."
    echo "${LAUNCH[$name]}"
  } > "$target"
  chmod +x "$target"
  made=$((made + 1))
done
echo "wrote $made shim(s) into $BIN"

# wake's summary on every new interactive Termux session -- added once,
# never duplicated (same block wake's own commit put in ~/.bashrc)
if ! grep -q "# --- wake:" "$HOME/.bashrc" 2>/dev/null; then
  cat >> "$HOME/.bashrc" <<'BASHRC'

# --- wake: mental check / task reminder / diagnostics summary ---
# Shown once per new interactive Termux session (not inside scripts or
# sessions opened by RUN_COMMAND). 15 s to pick one, enter skips.
case $- in
    *i*) [ -t 0 ] && [ -f "$HOME/bin/wake" ] && python3 "$HOME/bin/wake" start ;;
esac
BASHRC
  echo "added wake's startup summary to ~/.bashrc"
fi
