#!/data/data/com.termux/files/usr/bin/bash
# Creates/refreshes the $PREFIX/bin shims for every bare command whose
# real script lives in this folder -- run this once after cloning or
# pulling this repo on a NEW phone (or after pulling updates on either
# one) to make `overseer`, `programs`, etc. work as bare commands there
# too, not just python3 ~/bin/whatever.
#
# Requested directly, after Gabe clarified this device is the A17 (not
# the A33) and that he has both, personal, and wants them kept in
# program-sync: "i want you to keep them both in sync... i mean update
# same programs." Pulling this repo only updates the FILES in ~/bin --
# this script is the other half, wiring bare commands back up to them.
#
#     ~/bin/install.sh
#
# Safe to run as many times as you like -- each shim is just
# overwritten fresh, same as this script already did the first time.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
BIN="/data/data/com.termux/files/usr/bin"

# name -> (CATALOG line, how to launch it)
declare -A CATALOG=(
  [note3]="note3 -- posts a Termux notification with 3 custom buttons you define"
  [opensession]="opensession -- opens a brand-new, independent Termux session running any command"
  [overseer]="overseer -- one dashboard with /help/list/open/newsession, or \`overseer notify\` for a pinned reply notification"
  [programs]="programs -- lists every one of your own commands and starts one -- /help inside it"
  [termux-panel]="termux-panel -- add/remove a swipeable panel of extra keys on Termux's key row"
  [termux-sessions]="termux-sessions -- list/close Termux session tabs (kill <pid>, kill all, or all --include-self)"
  [timeweather]="timeweather -- shows and logs the current time + weather (wttr.in, no API key)"
  [updates]="updates -- check (and pull) GitHub updates for every project here: \`updates\`, \`updates pull <name-or-all>\`"
  [organize-files]="organize-files -- sorts loose files into type folders (dry-run by default, --apply to do it, --undo to reverse)"
)
# Only needed when the real script's filename isn't the command name
# itself (organize_files.py vs. organize-files) -- everything else is
# assumed to be $HERE/$name.
declare -A SOURCE=(
  [organize-files]="organize_files.py"
)
declare -A LAUNCH=(
  [note3]='exec "$HOME/bin/note3" "$@"'
  [opensession]='exec "$HOME/bin/opensession" "$@"'
  [overseer]='exec python3 "$HOME/bin/overseer" "$@"'
  [programs]='exec python3 "$HOME/bin/programs" "$@"'
  [termux-panel]='exec python3 "$HOME/bin/termux-panel" "$@"'
  [termux-sessions]='exec "$HOME/bin/termux-sessions" "$@"'
  [timeweather]='exec "$HOME/bin/timeweather" "$@"'
  [updates]='exec python3 "$HOME/bin/updates" "$@"'
  [organize-files]='exec python3 "$HOME/bin/organize_files.py" "$@"'
)

made=0
for name in "${!LAUNCH[@]}"; do
  source_file="${SOURCE[$name]:-$name}"
  if [ ! -f "$HERE/$source_file" ]; then
    echo "skipping $name -- $source_file not found in $HERE" >&2
    continue
  fi
  target="$BIN/$name"
  {
    echo '#!/data/data/com.termux/files/usr/bin/sh'
    echo "# CATALOG: ${CATALOG[$name]}"
    echo "# A thin launcher so \`$name\` works as a bare command -- the actual"
    echo "# script lives at ~/bin/$source_file. Regenerated by ~/bin/install.sh."
    echo "${LAUNCH[$name]}"
  } > "$target"
  chmod +x "$target"
  made=$((made + 1))
done
echo "wrote $made shim(s) into $BIN"
